In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df=pd.read_csv("Brainloxinfo.csv")

In [3]:
df

,courses name,price per session,no. of lessons,hour per session,Total price,Description,Session names
0,LEARN SCRATCH PROGRAMING,20,16,1,320,\nScratch Course is the foundation of coding a...,"Session 1Introduction to Scratch Programing,or..."
1,LEARN CLOUD COMPUTING BASICS-AWS,30,20,1,600,\nIn this course we are going to cover the bas...,"Session 1Introduction,order:1,Session 2Overvie..."
2,LEARN MOBILE DEVELOPMENT,20,24,1,480,\nMobile application development is the proces...,"Session 1Introduction,order:1,Session 2Learnin..."
3,LEARN CORE JAVA PROGRAMMING ONLINE,20,41,1,820,"\nJava is a very popular high-level, class-bas...",Session 1 Introduction to JAVA (History and Fe...
4,LEARN ROBOTICS,20,25,1,500,\nYou can open all kinds of doors for advancem...,"Session 1 Introduction to Robotics,order:1,Ses..."
...,...,...,...,...,...,...,...
62,Scratch Playground: Create a Space Game!,20,8,1,160,Scratch Playground : Create a Space Game is an...,NaN
63,Create Your Own Roblox Obstacle Course,20,8,1,160,Roblox enthusiasts who want to learn how to de...,NaN
64,Java Minecraft Creative or Survival Mode,20,7,1,140,1. Title: Minecraft Java Programming for Begin...,NaN
65,AI Camp for Jobs & Business:Build Your own Cha...,25,10,1,250,ðŸŒŸWelcome to the Chatbot Mastery Course! ðŸŽ“\n\nG...,NaN
66,"HTML, CSS, JavaScript Essentials: 5-Day Coding...",13,5,1,65,Unleash your creativity in our fun and interac...,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   courses name       67 non-null     object
 1   price per session  67 non-null     int64
 2   no. of lessons     67 non-null     int64
 3   hour per session   67 non-null     int64
 4   Total price        67 non-null     int64
 5   Description        67 non-null     object
 6   Session names      14 non-null     object
dtypes: int64(4), object(3)
memory usage: 3.8+ KB

In [5]:
df['Session names'] = df['Session names'].fillna("Coming Soon")

In [6]:
df['Description']=df.Description.astype("str")

In [7]:
def clean(text):
    text=text.replace("\n","")
    text=text.replace("\t","")
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # Emoticons
        "\U0001F300-\U0001F5FF"  # Symbols & Pictographs
        "\U0001F680-\U0001F6FF"  # Transport & Map Symbols
        "\U0001F700-\U0001F77F"  # Alchemical Symbols
        "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U0001FA00-\U0001FA6F"  # Chess Symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U0001F004-\U0001F0CF"  # Miscellaneous Symbols and Arrows
        "\U0001F170-\U0001F251"  # Enclosed Characters
        "]+",
        flags=re.UNICODE,
    )
    # Use sub() method to replace emojis with an empty string
    text_without_emojis = emoji_pattern.sub(r"", text)
    # Define a regular expression pattern to match symbols, signs, and operators
    pattern = r'[!@#$%^&*()_+={}\[\]:;"\'<>,.?/\|\\`~]'

    # Use the re.sub() function to remove the matched characters
    cleaned_string = re.sub(pattern, '', text_without_emojis)
    return cleaned_string

In [8]:
df["Description"]=df["Description"].apply(clean)

In [9]:
df["Session names"]=df["Session names"].apply(clean)

In [10]:
df

,courses name,price per session,no. of lessons,hour per session,Total price,Description,Session names
0,LEARN SCRATCH PROGRAMING,20,16,1,320,Scratch Course is the foundation of coding and...,Session 1Introduction to Scratch Programingord...
1,LEARN CLOUD COMPUTING BASICS-AWS,30,20,1,600,In this course we are going to cover the basic...,Session 1Introductionorder1Session 2Overview A...
2,LEARN MOBILE DEVELOPMENT,20,24,1,480,Mobile application development is the process ...,Session 1Introductionorder1Session 2Learning a...
3,LEARN CORE JAVA PROGRAMMING ONLINE,20,41,1,820,Java is a very popular high-level class-based ...,Session 1 Introduction to JAVA History and Fea...
4,LEARN ROBOTICS,20,25,1,500,You can open all kinds of doors for advancemen...,Session 1 Introduction to Roboticsorder1Sessio...
...,...,...,...,...,...,...,...
62,Scratch Playground: Create a Space Game!,20,8,1,160,Scratch Playground Create a Space Game is an ...,Coming Soon
63,Create Your Own Roblox Obstacle Course,20,8,1,160,Roblox enthusiasts who want to learn how to de...,Coming Soon
64,Java Minecraft Creative or Survival Mode,20,7,1,140,1 Title Minecraft Java Programming for Beginne...,Coming Soon
65,AI Camp for Jobs & Business:Build Your own Cha...,25,10,1,250,Welcome to the Chatbot Mastery Course Get read...,Coming Soon
66,"HTML, CSS, JavaScript Essentials: 5-Day Coding...",13,5,1,65,Unleash your creativity in our fun and interac...,Coming Soon

In [11]:
df.to_csv("brainloxinfoclean.csv",index=False)

In [12]:
df.columns

Index(['courses name', 'price per session', 'no. of lessons',
       'hour per session', 'Total price', 'Description', 'Session names'],
      dtype='object')